name: Build arm64 Apps
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
#  update-submodules:
#    runs-on: ubuntu-latest

#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#        with:
#          submodules: true  # Automatisch Submodule beim Checkout initialisieren

 #     - name: Clone this repository
 #       run: |
 #         git clone --recurse-submodules https://github.com/s3tupw1zard/raspi-apps .

 #     - name: Verify submodule update
 #       run: git submodule status



  build-greenlight:
    name: Build Greenlight
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        run: echo "GH_TOKEN=${{ secrets.PAT_TOKEN }}" >> $GITHUB_ENV
#      - uses: actions/checkout@v3
      - name: Clone this repository into current folder
        run: |
          git clone --recurse-submodules https://github.com/s3tupw1zard/raspi-apps .

      - name: Initialize submodules for Greenlight
        run: |
          cd greenlight
          git submodule update --init --recursive
          ls -l

      - name: Set Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: greenlight

      - name: Build Greenlight app deb file and AppImage for x64
        run: |
          cd greenlight
          yarn build

      - name: Build Greenlight app deb file and AppImage for arm64
        run: |
          cd greenlight
          npx electron-builder --arm64

      - name: Release Greenlight
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          tag_name: greenlight
          body_path: greenlight/CHANGELOG.md
          files: |
            greenlight/dist/greenlight*.deb
            greenlight/dist/greenlight*.AppImage
